/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "background": "#f8f9fa",
        "inverse-primary": "#95d4b3",
        "surface-container": "#edeeef",
        "on-secondary-fixed": "#001d32",
        "secondary-fixed-dim": "#94ccff",
        "outline-variant": "#bfc9c1",
        "tertiary-container": "#456900",
        "on-secondary-container": "#004972",
        "on-tertiary-fixed": "#121f00",
        "surface": "#f8f9fa",
        "on-secondary": "#ffffff",
        "surface-variant": "#e1e3e4",
        "on-error-container": "#93000a",
        "on-background": "#191c1d",
        "on-tertiary-container": "#aeec50",
        "outline": "#707973",
        "on-primary-fixed": "#002114",
        "on-primary-container": "#a8e7c5",
        "surface-dim": "#d9dadb",
        "secondary": "#006399",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#e7e8e9",
        "inverse-on-surface": "#f0f1f2",
        "on-primary": "#ffffff",
        "tertiary": "#334f00",
        "on-surface": "#191c1d",
        "surface-tint": "#2c694e",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed-variant": "#004b74",
        "secondary-container": "#67bafd",
        "error": "#ba1a1a",
        "primary": "#0f5238",
        "primary-container": "#2d6a4f",
        "on-surface-variant": "#404943",
        "inverse-surface": "#2e3132",
        "tertiary-fixed-dim": "#9cd83e",
        "on-primary-fixed-variant": "#0e5138",
        "surface-container-low": "#f3f4f5",
        "primary-fixed": "#b1f0ce",
        "surface-container-highest": "#e1e3e4",
        "tertiary-fixed": "#b7f558",
        "on-error": "#ffffff",
        "primary-fixed-dim": "#95d4b3",
        "secondary-fixed": "#cde5ff",
        "surface-bright": "#f8f9fa",
        "error-container": "#ffdad6",
        "on-tertiary-fixed-variant": "#324f00"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px"
      },
      fontFamily: {
        "headline": ["Plus Jakarta Sans", "sans-serif"],
        "body": ["Be Vietnam Pro", "sans-serif"],
        "label": ["Plus Jakarta Sans", "sans-serif"]
      }
    },
  },
  plugins: [],
}
